### ISSUE TITLE
Lighthouse Error

### ISSUE THREAD

**Issue by aress31** [siriwatknp/mui-treasury#1158]
I think that this console error is caused by the library rather than my own code, here is the stack trace:

```
Warning: React does not recognize the `styleProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `styleprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:868:73
    at Drawer (http://localhost:3000/static/js/vendors~main.chunk.js:14345:87)
    at http://localhost:3000/static/js/vendors~main.chunk.js:868:73
    at EdgeSidebar (http://localhost:3000/static/js/vendors~main.chunk.js:283950:5)
    at Root (http://localhost:3000/static/js/vendors~main.chunk.js:285746:19)
    at push../src/App.js.__webpack_exports__.default (http://localhost:3000/static/js/main.chunk.js:2339:88)
    at InnerThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:274339:74)
    at ThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:273921:5)
    at ThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:274359:5)
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:330435:5)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:329933:5)
    at Index (http://localhost:3000/static/js/main.chunk.js:3468:105)
```

**Comment by siriwatknp** [comment]
which layout version do you use?
