### ISSUE TITLE
Add an example with next.js

### ISSUE THREAD

**Issue by neyasov** [siriwatknp/mui-treasury#286]
```
Unexpected token 'export'
/my-app/node_modules/@mui-treasury/layout/index.js:1
export * from './components';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.@mui-treasury/layout (/my-app/.next/server/static/development/pages/index.js:2444:18)
    at __webpack_require__ (/my-app/.next/server/static/development/pages/index.js:23:31)
    at Module../pages/index.js (/my-app/.next/server/static/development/pages/index.js:2264:78)
    at __webpack_require__ (/my-app/.next/server/static/development/pages/index.js:23:31)
    at Object.3 (/my-app/.next/server/static/development/pages/index.js:2432:18)
    at __webpack_require__ (/my-app/.next/server/static/development/pages/index.js:23:31)
    at /my-app/.next/server/static/development/pages/index.js:91:18
    at Object.<anonymous> (/my-app/.next/server/static/development/pages/index.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```

**Comment by siriwatknp** [comment]
@neyasov thanks for opening the issue. will update soon!
