### ISSUE TITLE
Invalid makeStyles references

### ISSUE THREAD

**Issue by devth** [siriwatknp/mui-treasury#517]
Awesome lib, nice work!

I noticed on latest `"@mui-treasury/styles": "^0.5.0",` when trying to use:

```javascript
import { useSoftRiseShadowStyles } from '@mui-treasury/styles/shadow/softRise';
```

I see runtime errors:

```
import makeStyles from '@material-ui/core/styles/makeStyles';
       ^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

**Comment by siriwatknp** [comment]
What framework r u using? is it Nextjs

**Comment by devth** [comment]
Yep.

**Comment by siriwatknp** [comment]
Please look at Nextjs starter project. Need to transpile to cjs
https://github.com/siriwatknp/mui-treasury/blob/master/starters/nextjs/next.config.js

**Comment by devth** [comment]
Got it, thanks!
