### ISSUE TITLE
SSR bug with next.js 3.4

### ISSUE THREAD

**Issue by neyasov** [siriwatknp/mui-treasury#785]
```
TypeError: Cannot read property 'undefined' of undefined
     at pickNearestBreakpoint (/workspace/node_modules/@mui-treasury/layout/utils/pickNearestBreakpoint.js:16:11)
     at useBreakpointConfig (/workspace/node_modules/@mui-treasury/layout/hooks/useBreakpointConfig.js:16:43)
    at DrawerSidebar (/workspace/node_modules/@mui-treasury/layout/components/DrawerSidebar/DrawerSidebar.js:83:49)
```

**Comment by siriwatknp** [comment]
Can you provide the code?
