### ISSUE TITLE
Attempted import error: 'keys' is not exported from '@material-ui/core/styles/createBreakpoints'.

### ISSUE THREAD

**Issue by vmptk** [siriwatknp/mui-treasury#971]
The MUI 5.x will have breaking changes:

```

error - ./node_modules/@mui-treasury/layout/esm/hooks/useSidebarAutoCollapse.js
Attempted import error: 'keys' is not exported from '@material-ui/core/styles/createBreakpoints'.
...node_modules/@material-ui/core/styles/createBreakpoints.js:1
import _extends from "@babel/runtime/helpers/esm/extends";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (../node_modules/@mui-treasury/layout/utils/pickNearestBreakpoint.js:8:26)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
.../node_modules/@material-ui/core/styles/createBreakpoints.js:1
import _extends from "@babel/runtime/helpers/esm/extends";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (.../node_modules/@mui-treasury/layout/utils/pickNearestBreakpoint.js:8:26)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)

```

**Comment by siriwatknp** [comment]
Thanks for reporting the issue. Material-UI v5 is not supported yet.
